/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'hero-banners': HeroBanner;
    faqs: Faq;
    services: Service;
    testimonials: Testimonial;
    'smartphone-products': SmartphoneProduct;
    'blog-posts': BlogPost;
    'financing-pages': FinancingPage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'hero-banners': HeroBannersSelect<false> | HeroBannersSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'smartphone-products': SmartphoneProductsSelect<false> | SmartphoneProductsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'financing-pages': FinancingPagesSelect<false> | FinancingPagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ms') | ('en' | 'ms')[];
  globals: {
    'site-settings': SiteSetting;
    'home-impact': HomeImpact;
    'about-partner': AboutPartner;
    eligibility: Eligibility;
    terms: Term;
    privacy: Privacy;
    'apply-settings': ApplySetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-impact': HomeImpactSelect<false> | HomeImpactSelect<true>;
    'about-partner': AboutPartnerSelect<false> | AboutPartnerSelect<true>;
    eligibility: EligibilitySelect<false> | EligibilitySelect<true>;
    terms: TermsSelect<false> | TermsSelect<true>;
    privacy: PrivacySelect<false> | PrivacySelect<true>;
    'apply-settings': ApplySettingsSelect<false> | ApplySettingsSelect<true>;
  };
  locale: 'en' | 'ms';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describes the image for screen readers and SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Slides in the homepage hero carousel. Drag order via the Order field. EN/BM edited with the language switch.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-banners".
 */
export interface HeroBanner {
  id: number;
  /**
   * Only shown in the admin — not on the website.
   */
  internalName: string;
  enabled?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Colour of the eyebrow text.
   */
  accent: 'sky' | 'gold';
  /**
   * Small uppercase label above the title.
   */
  eyebrow: string;
  /**
   * Main headline. Press Enter for a line break.
   */
  title: string;
  body: string;
  backgroundImage: number | Media;
  /**
   * Destination for the "Apply Now" button.
   */
  applyHref: string;
  /**
   * Destination for the "How It Works" button.
   */
  howItWorksHref: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Frequently asked questions. Set the Category to control where each one appears. EN/BM edited with the language switch.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  /**
   * Which FAQ list this question belongs to.
   */
  category:
    | 'home-motorcycle'
    | 'home-smartphone'
    | 'motorcycle-page'
    | 'smartphone-page'
    | 'resources-motorcycle'
    | 'resources-smartphone';
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Items in the navbar Services dropdown.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Label shown in the dropdown.
   */
  name: string;
  /**
   * Path for the English site, e.g. "/financing-hp". The /ms prefix is added automatically on the Malay site.
   */
  href: string;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer reviews shown on the homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  authorName: string;
  /**
   * Shown under the name, e.g. "Motorcycle Owner · Kuching".
   */
  descriptor?: string | null;
  /**
   * Featured reviews render large on the left. Keep one or two featured.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Product cards in the smartphone lineup section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "smartphone-products".
 */
export interface SmartphoneProduct {
  id: number;
  /**
   * e.g. "iPhone 17 Pro".
   */
  name: string;
  description: string;
  image: number | Media;
  /**
   * Destination for the card's "Apply Now" button.
   */
  applyHref?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Articles for the Resources section. EN/BM edited with the language switch — the slug can differ per language.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * URL segment, e.g. ccris-ctos-can-you-still-get-a-motorcycle-loan. Lowercase, words separated by hyphens.
   */
  slug: string;
  /**
   * Controls ordering (newest first).
   */
  publishedAt?: string | null;
  enabled?: boolean | null;
  /**
   * e.g. "5 min read".
   */
  readingTime?: string | null;
  excerpt: string;
  /**
   * Cover image. Leave blank to use the external image URL below instead.
   */
  image?: (number | null) | Media;
  /**
   * Optional external cover image URL (used only if no cover image is uploaded).
   */
  imageUrl?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional call-to-action box shown at the end of the article (with "Calculate Instalment" and "Apply Now" buttons).
   */
  callout?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Product financing pages. Duplicate one to add a new product page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financing-pages".
 */
export interface FinancingPage {
  id: number;
  /**
   * Admin title, e.g. "Smartphone HP Financing".
   */
  title: string;
  /**
   * URL segment — the page lives at /financing/<slug>. Lowercase, dashes, e.g. "laptop-hp".
   */
  slug: string;
  enabled?: boolean | null;
  hero?: {
    eyebrow?: string | null;
    /**
     * Colour of the eyebrow label.
     */
    accent?: ('gold' | 'sky') | null;
    /**
     * Use a line break for a two-line title.
     */
    title?: string | null;
    body?: string | null;
    backgroundImage?: (number | null) | Media;
    /**
     * Optional: external image URL, used if no upload is set.
     */
    backgroundImageUrl?: string | null;
    applyHref?: string | null;
    applyLabel?: string | null;
  };
  whyUs?: {
    heading?: string | null;
    cards?:
      | {
          icon?:
            | (
                | 'calendar'
                | 'bolt'
                | 'percent'
                | 'clock'
                | 'apple'
                | 'person'
                | 'document'
                | 'income'
                | 'shield'
                | 'chart'
              )
            | null;
          title?: string | null;
          desc?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  lineup?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    heading?: string | null;
    body?: string | null;
    products?:
      | {
          image?: (number | null) | Media;
          /**
           * Used if no upload is set.
           */
          imageUrl?: string | null;
          name?: string | null;
          desc?: string | null;
          applyHref?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  eligibility?: {
    eyebrow?: string | null;
    heading?: string | null;
    intro?: string | null;
    checkLabel?: string | null;
    checkHref?: string | null;
    pdsLabel?: string | null;
    pdsUrl?: string | null;
    rows?:
      | {
          icon?:
            | (
                | 'calendar'
                | 'bolt'
                | 'percent'
                | 'clock'
                | 'apple'
                | 'person'
                | 'document'
                | 'income'
                | 'shield'
                | 'chart'
              )
            | null;
          label?: string | null;
          value?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  calculator?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    heading?: string | null;
    body?: string | null;
    minAmount?: number | null;
    maxAmount?: number | null;
    step?: number | null;
    defaultAmount?: number | null;
    defaultTenure?: number | null;
    /**
     * Comma-separated month options, e.g. 12,24,36.
     */
    tenures?: string | null;
    pdsUrl?: string | null;
  };
  faq?:
    | {
        question: string;
        answer?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    heading?: string | null;
    body?: string | null;
    buttonLabel?: string | null;
    buttonHref?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'hero-banners';
        value: number | HeroBanner;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'smartphone-products';
        value: number | SmartphoneProduct;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'financing-pages';
        value: number | FinancingPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-banners_select".
 */
export interface HeroBannersSelect<T extends boolean = true> {
  internalName?: T;
  enabled?: T;
  order?: T;
  accent?: T;
  eyebrow?: T;
  title?: T;
  body?: T;
  backgroundImage?: T;
  applyHref?: T;
  howItWorksHref?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  category?: T;
  order?: T;
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  href?: T;
  order?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  authorName?: T;
  descriptor?: T;
  featured?: T;
  order?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "smartphone-products_select".
 */
export interface SmartphoneProductsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  image?: T;
  applyHref?: T;
  order?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  enabled?: T;
  readingTime?: T;
  excerpt?: T;
  image?: T;
  imageUrl?: T;
  body?: T;
  callout?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financing-pages_select".
 */
export interface FinancingPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  enabled?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        accent?: T;
        title?: T;
        body?: T;
        backgroundImage?: T;
        backgroundImageUrl?: T;
        applyHref?: T;
        applyLabel?: T;
      };
  whyUs?:
    | T
    | {
        heading?: T;
        cards?:
          | T
          | {
              icon?: T;
              title?: T;
              desc?: T;
              id?: T;
            };
      };
  lineup?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        heading?: T;
        body?: T;
        products?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              name?: T;
              desc?: T;
              applyHref?: T;
              id?: T;
            };
      };
  eligibility?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
        checkLabel?: T;
        checkHref?: T;
        pdsLabel?: T;
        pdsUrl?: T;
        rows?:
          | T
          | {
              icon?: T;
              label?: T;
              value?: T;
              id?: T;
            };
      };
  calculator?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        heading?: T;
        body?: T;
        minAmount?: T;
        maxAmount?: T;
        step?: T;
        defaultAmount?: T;
        defaultTenure?: T;
        tenures?: T;
        pdsUrl?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        heading?: T;
        body?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Footer, contact details, social links, WhatsApp, PDS links and the contact map. Shared across the whole site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName?: string | null;
  registrationNo?: string | null;
  /**
   * One line per row (press Enter for a new line).
   */
  address?: string | null;
  operatingHours?: {
    days?: string | null;
    time?: string | null;
  };
  phone?: string | null;
  email?: string | null;
  /**
   * Digits only, including country code (e.g. 60169328901). Used for the wa.me link and the floating WhatsApp button.
   */
  whatsappNumber?: string | null;
  /**
   * How the number is shown to visitors.
   */
  whatsappDisplay?: string | null;
  social?: {
    instagram?: string | null;
    facebook?: string | null;
    tiktok?: string | null;
  };
  motorcyclePdsUrl?: string | null;
  smartphonePdsUrl?: string | null;
  /**
   * The "src" URL from Google Maps → Share → Embed a map. Used for the map on the Contact page.
   */
  mapEmbedSrc?: string | null;
  /**
   * Where the Open in Maps button points.
   */
  mapLink?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The "Our Impact" section with the motorcycle/smartphone toggle and editable stat cards.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-impact".
 */
export interface HomeImpact {
  id: number;
  eyebrow?: string | null;
  motorcycle: {
    /**
     * Label on the toggle button.
     */
    tab: string;
    heading: string;
    body: string;
    buttonText?: string | null;
    /**
     * e.g. "/financing-hp".
     */
    buttonHref?: string | null;
    plate?: {
      image?: (number | null) | Media;
      eyebrow?: string | null;
      text?: string | null;
      /**
       * Optional corner badge.
       */
      badge?: string | null;
    };
    /**
     * The stat cards on the right of the bento.
     */
    stats?:
      | {
          /**
           * e.g. "90%", "60", "24–48h". Leave blank for a label-only card.
           */
          value?: string | null;
          style?: ('light' | 'navy') | null;
          icon?:
            | (
                | 'calendar'
                | 'bolt'
                | 'percent'
                | 'clock'
                | 'apple'
                | 'person'
                | 'document'
                | 'income'
                | 'shield'
                | 'chart'
              )
            | null;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  smartphone: {
    /**
     * Label on the toggle button.
     */
    tab: string;
    heading: string;
    body: string;
    buttonText?: string | null;
    /**
     * e.g. "/financing-hp".
     */
    buttonHref?: string | null;
    plate?: {
      image?: (number | null) | Media;
      eyebrow?: string | null;
      text?: string | null;
      /**
       * Optional corner badge.
       */
      badge?: string | null;
    };
    /**
     * The stat cards on the right of the bento.
     */
    stats?:
      | {
          /**
           * e.g. "90%", "60", "24–48h". Leave blank for a label-only card.
           */
          value?: string | null;
          style?: ('light' | 'navy') | null;
          icon?:
            | (
                | 'calendar'
                | 'bolt'
                | 'percent'
                | 'clock'
                | 'apple'
                | 'person'
                | 'document'
                | 'income'
                | 'shield'
                | 'chart'
              )
            | null;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The "Our Partner" block on the About page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-partner".
 */
export interface AboutPartner {
  id: number;
  eyebrow?: string | null;
  heading: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Partner logo shown on the right.
   */
  logo?: (number | null) | Media;
  linkLabel?: string | null;
  linkUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The Eligibility & Documents tables on the Motorcycle and Smartphone financing pages. PDS links are edited in Site Settings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eligibility".
 */
export interface Eligibility {
  id: number;
  motorcycle: {
    eyebrow?: string | null;
    heading: string;
    /**
     * Short paragraph under the heading.
     */
    intro?: string | null;
    /**
     * Each requirement row in the table.
     */
    rows?:
      | {
          icon?:
            | (
                | 'calendar'
                | 'bolt'
                | 'percent'
                | 'clock'
                | 'apple'
                | 'person'
                | 'document'
                | 'income'
                | 'shield'
                | 'chart'
              )
            | null;
          /**
           * e.g. "Nationality".
           */
          label: string;
          /**
           * e.g. "Malaysian Citizen".
           */
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  smartphone: {
    eyebrow?: string | null;
    heading: string;
    /**
     * Short paragraph under the heading.
     */
    intro?: string | null;
    /**
     * Each requirement row in the table.
     */
    rows?:
      | {
          icon?:
            | (
                | 'calendar'
                | 'bolt'
                | 'percent'
                | 'clock'
                | 'apple'
                | 'person'
                | 'document'
                | 'income'
                | 'shield'
                | 'chart'
              )
            | null;
          /**
           * e.g. "Nationality".
           */
          label: string;
          /**
           * e.g. "Malaysian Citizen".
           */
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Editable content for the Terms of Service page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms".
 */
export interface Term {
  id: number;
  title?: string | null;
  /**
   * Full page content. Use headings for each section. Leave empty to show the built-in default.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Editable content for the Privacy Notice page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy".
 */
export interface Privacy {
  id: number;
  title?: string | null;
  /**
   * Full page content. Use headings for each section. Leave empty to show the built-in default.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Enable/disable each financing application form, edit its label, and choose which questions it asks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apply-settings".
 */
export interface ApplySetting {
  id: number;
  motorcycleEnabled?: boolean | null;
  motorcycleLabel?: string | null;
  smartphoneEnabled?: boolean | null;
  smartphoneLabel?: string | null;
  motorcycleFields?: {
    financingDetails?: {
      condition?: boolean | null;
      brand?: boolean | null;
      year?: boolean | null;
      tenure?: boolean | null;
      price?: boolean | null;
      downpayment?: boolean | null;
    };
    /**
     * Turn every question in this step off and the step is skipped entirely.
     */
    financialProfile?: {
      employment?: boolean | null;
      salary?: boolean | null;
      commitments?: boolean | null;
      location?: boolean | null;
      creditIssues?: boolean | null;
    };
    /**
     * Full Name, Phone Number and the PDPA consent are always asked — they are the minimum needed to follow up on a lead lawfully.
     */
    personalDetails?: {
      age?: boolean | null;
      nric?: boolean | null;
      email?: boolean | null;
      preferredComm?: boolean | null;
      payslip?: boolean | null;
    };
  };
  smartphoneFields?: {
    financingDetails?: {
      deviceModel?: boolean | null;
      smartphoneTenure?: boolean | null;
    };
    /**
     * Turn every question in this step off and the step is skipped entirely.
     */
    financialProfile?: {
      employment?: boolean | null;
      salary?: boolean | null;
      commitments?: boolean | null;
      location?: boolean | null;
      creditIssues?: boolean | null;
    };
    /**
     * Full Name, Phone Number and the PDPA consent are always asked — they are the minimum needed to follow up on a lead lawfully.
     */
    personalDetails?: {
      age?: boolean | null;
      nric?: boolean | null;
      email?: boolean | null;
      preferredComm?: boolean | null;
      payslip?: boolean | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  registrationNo?: T;
  address?: T;
  operatingHours?:
    | T
    | {
        days?: T;
        time?: T;
      };
  phone?: T;
  email?: T;
  whatsappNumber?: T;
  whatsappDisplay?: T;
  social?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        tiktok?: T;
      };
  motorcyclePdsUrl?: T;
  smartphonePdsUrl?: T;
  mapEmbedSrc?: T;
  mapLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-impact_select".
 */
export interface HomeImpactSelect<T extends boolean = true> {
  eyebrow?: T;
  motorcycle?:
    | T
    | {
        tab?: T;
        heading?: T;
        body?: T;
        buttonText?: T;
        buttonHref?: T;
        plate?:
          | T
          | {
              image?: T;
              eyebrow?: T;
              text?: T;
              badge?: T;
            };
        stats?:
          | T
          | {
              value?: T;
              style?: T;
              icon?: T;
              label?: T;
              id?: T;
            };
      };
  smartphone?:
    | T
    | {
        tab?: T;
        heading?: T;
        body?: T;
        buttonText?: T;
        buttonHref?: T;
        plate?:
          | T
          | {
              image?: T;
              eyebrow?: T;
              text?: T;
              badge?: T;
            };
        stats?:
          | T
          | {
              value?: T;
              style?: T;
              icon?: T;
              label?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-partner_select".
 */
export interface AboutPartnerSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  logo?: T;
  linkLabel?: T;
  linkUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eligibility_select".
 */
export interface EligibilitySelect<T extends boolean = true> {
  motorcycle?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
        rows?:
          | T
          | {
              icon?: T;
              label?: T;
              value?: T;
              id?: T;
            };
      };
  smartphone?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
        rows?:
          | T
          | {
              icon?: T;
              label?: T;
              value?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms_select".
 */
export interface TermsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy_select".
 */
export interface PrivacySelect<T extends boolean = true> {
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apply-settings_select".
 */
export interface ApplySettingsSelect<T extends boolean = true> {
  motorcycleEnabled?: T;
  motorcycleLabel?: T;
  smartphoneEnabled?: T;
  smartphoneLabel?: T;
  motorcycleFields?:
    | T
    | {
        financingDetails?:
          | T
          | {
              condition?: T;
              brand?: T;
              year?: T;
              tenure?: T;
              price?: T;
              downpayment?: T;
            };
        financialProfile?:
          | T
          | {
              employment?: T;
              salary?: T;
              commitments?: T;
              location?: T;
              creditIssues?: T;
            };
        personalDetails?:
          | T
          | {
              age?: T;
              nric?: T;
              email?: T;
              preferredComm?: T;
              payslip?: T;
            };
      };
  smartphoneFields?:
    | T
    | {
        financingDetails?:
          | T
          | {
              deviceModel?: T;
              smartphoneTenure?: T;
            };
        financialProfile?:
          | T
          | {
              employment?: T;
              salary?: T;
              commitments?: T;
              location?: T;
              creditIssues?: T;
            };
        personalDetails?:
          | T
          | {
              age?: T;
              nric?: T;
              email?: T;
              preferredComm?: T;
              payslip?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}